sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 2.7
        - python: 3.4
notifications:
    email: false
install:
  # source: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pytest
  - source activate test-environment
  - pip install pep8 pytest-pep8 pytest-xdist
  - pip install python-coveralls pytest-cov
  - python setup.py install
script:
  - PYTHONPATH=$PWD:$PYTHONPATH pytest --cov=observations --pep8;
after_success:
  - coveralls
